# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jeckel-Lab
email: contact@jeckel-lab.fr
description: >- # this means to ignore newlines until "baseurl:"
  Freelance : Expert PHP / Lead Developer / Software Architect
  J'accompagne les équipes IT dans l'industrialisation de leurs projets Web, à la fois sur l'architecture, la qualité et l'intégration continue, la gestion de projet et l'agilité.
image:
  path: /assets/images/Jeckel-Lab-rounded.png
  height: 500
  width: 500
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeckel-lab.fr"
twitter_username: jeckel4
github_username:  jeckel
linkedin_username: jeckel
rss: RSS
mastodon:
  - username: jeckel
    instance: phpc.social

highlighter: none
author: Julien Mercier-Rojas
lang: fr

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap

collections:
  tags:
    output: true
    permalink: tag/:title/

defaults:
  - scope:
      path: ""
      type: tags
    values:
      layout: tag

sass:
  style: compressed

exclude:
  - Makefile
  - .idea/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
